####### Pretty sure this can be removed ##########


# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#development:
#  secret_key_base: eb8e6a802f9ed465ed94f340bae79a0fcce9f9a40f2c9e4ef41ff441d339fb8c4a97e3efdd51db94fdb16b54ba8454d7f1dc2a2cbedc1391dfa29075d1dc6265
#
#test:
#  secret_key_base: 1db27be67e24bfd289153b3bd8a332203b7d682ef7812333a67198b89becbc25e0cde348f54ed7bc288d7c1b38957dfb723c9b5435100c4bd8f931a83ffa16ef
#
## Do not keep production secrets in the repository,
## instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
